services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data 
    ports:
      - 5432:5432
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 3001:3001
 
volumes:
  pgdata: